# Welcome to Jekyll!

# Website settings
title: "柠檬水"
description: "blog,use Jekyll and github pages."
keywords: "zhuliwei,柠檬水,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "https://hytczhuliwei.github.io/"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'static/img/landing/avatar_self.jpg'

# author
author:
  name: '朱立威'
  first_name: '立威'
  last_name: '朱'
  email: '543367517@qq.com'
  facebook_username: 'none'
  github_username: 'hytczhuliwei'
  head_img: 'static/img/landing/avatar_self.jpg'

# social link
test:
  first_name: 'test'
  last_name: '1'
  description: 'Painter.'
  link: 'http://angular.test.com'
  email: '3378258@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  24tidy:
    name: '24tidy'
    url: 'https://m.24tidy.com/'
    img: 'static/img/landing/24tidy.png'
  staticPage:
    name: '静态页面'
    url: 'staticPage/'
    img: 'static/img/landing/staticPage.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
